config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"
  resources :users, only: [:index, :show, :create] do
    member do
      get :followings
      get :followers
      
      get :likes
    end
  end
  
  
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post, class_name: "Micropost"
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  
  has_many :favorites
  has_many :favorite_user, through: :favorites, source: :user_id
  
  validates :content, presence: true, length: {maximum: 255}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
    has_many :microposts
    
    has_many :relationships
    has_many :followings, through: :relationships, source: :follow
    has_many :reverse_of_relationship, class_name: "Relationship", foreign_key: "follow_id"
    has_many :followers, through: :reverse_of_relationship, source: :user
    
    has_many :favorites
    has_many :favorite_post, through: :favorites, source: :post
    
    validates :name, presence: true, length: {maximum: 50}
    validates :email, presence: true, length: {maximum: 255}, format: {with: /\A[\w\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}, uniqueness: {case_sensitive: false}
    
    before_save {self.email.downcase!}
    
    has_secure_password
    
    # フォロー機能
    def follow(other_user)
        unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id) #Relationshipのインスタンスを返す
        end
    end
    
    def unfollow(other_user)
        relationship = self.relationships.find_by(follow_id: other_user.id)
        relationship.destroy if relationship
    end
    
    def following?(other_user)
        self.followings.include?(other_user)
    end
    
    # タイムライン
    def feed_microposts
        Micropost.where(user_id: self.following_ids + [self.id])
    end
    
    # お気に入り機能
    def favorite(post_item)
        self.favorites.find_or_create_by(post_id: post_item.id)
    end
    
    def unfavorite(post_item)
        favorite = self.favorites.find_by(post_id: post_item.id)
        favorite.destroy if favorite
    end
    
    def favorite?(post_item)
        self.favorite_post.include?(post_item)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend
    include SessionsHelper
    
    private
    
    def require_user_logged_in
        unless logged_in?
            redirect_to login_url
        end
    end
    
    def counts(user)
        @count_posts = user.microposts.count
        
        @count_followings = user.followings.count
        @count_followers = user.followers.count
        
        @count_favorites = user.favorites.count
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    fav_post = Micropost.find(params[:post_id])
    
    current_user.favorite(fav_post)
    flash[:success] = "お気に入り登録しました。"
    redirect_to likes_user_url(current_user)
  end

  def destroy
    fav_post = Micropost.find(params[:post_id])
    
    current_user.unfavorite(fav_post)
    flash[:danger] = "お気に入りを解除しました。"
    redirect_to likes_user_url(current_user)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    
    if @micropost.save
      flash[:success] = "メッセージを投稿しました。"
      redirect_to root_url
    else
      @pagy, @microposts = pagy(current_user.feed_microposts.order(id: :desc)) #toppages/indexはアクションの処理をせずにtoppage.html.erbを返すだけのためインスタンスが必要
      flash.now[:danger] = "メッセージの投稿に失敗しました。"
      render "toppages/index", status: :unprocessable_entity #status: :unprocessable_entity rails7.0以降追記が必要
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "メッセージを削除しました。"
    redirect_back(fallback_location: root_path) #アクションが実行されたページに戻るメソッド
  end
  
  
  private
  
  def micropost_params
    params.require(:micropost).permit(:content)
  end
  
  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    unless @micropost #nil, falseの時に実行される
      redirect_to root_url
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    user = User.find(params[:follow_id])
    
    current_user.follow(user)
    flash[:success] = "ユーザをフォローしました。"
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    
    current_user.unfollow(user)
    flash[:danger] = "ユーザのフォローを解除しました。"
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    if login(email, password)
      flash[:success] = "ログインに成功しました。"
      redirect_to @user
    else
      flash.now[:danger] = "ログインに失敗しました。"
      render :new, status: :unprocessable_entity #status: :unprocessable_entity rails7.0以降追記が必要
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました。"
    redirect_to root_url
  end
  
  
  private
  
  # ログイン処理
  def login(email, password)
    @user = User.find_by(email: email)
    
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @micropost = current_user.microposts.build
      @pagy, @microposts = pagy(current_user.feed_microposts.order(id: :desc))
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers]
  before_action :find_user, only: [:show, :followings, :followers, :likes]
  before_action :count_user, only: [:show, :followings, :followers, :likes]
  
  def index
    @pagy, @users = pagy(User.order(id: :desc), items: 15)
  end

  def show
    @pagy, @microposts = pagy(@user.microposts.order(id: :desc))
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザを登録しました。"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザの登録に失敗しました。"
      render :new, status: :unprocessable_entity #status: :unprocessable_entity rails7.0以降追記が必要
    end
  end
  
  def followings
    @pagy, @followings = pagy(@user.followings)
  end
    
  def followers
    @pagy, @followers = pagy(@user.followers)
  end
  
  def likes
    @pagy, @favorites = pagy(@user.favorite_post)
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def find_user
    @user = User.find(params[:id])
  end
  
  def count_user
    counts(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # 現在ログインしているユーザを取得
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    # ログインしているか確認
    def logged_in?
        !!current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    end
end

app/views/favorites/_favorite_button.html.erb
<% if current_user.favorite?(post_item) %>
    <%= form_with(model: current_user.favorites.find_by(post_id: post_item.id), method: :delete) do |f| %>
        <%= hidden_field_tag :post_id, post_item.id %>
        <%= f.submit "Unfavorite", class: "btn btn-danger bt-sm" %>
    <% end %>
<% else %>
    <%= form_with(model: current_user.favorites.build) do |f| %>
        <%= hidden_field_tag :post_id, post_item.id %>
        <%= f.submit "Favorite", class: "btn btn-primary bt-sm" %>
    <% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<%#= form_with(model: @user) do |f| %>
<% if model.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
        <ul class="mb-0">
            <% model.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
    <div class="alert alert-<%= msg_type %>"><%= msg %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container-fluid ps-5 pe-5">
            <a class="navbar-brand" href="/">Microposts</a>
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarSC">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!--ログイン状況で変化-->
            <div id="navbarSC" class="collapse navbar-collapse justify-content-end">
                <% if logged_in? %>
                    <div class="btn-group">
                        <ul class="navbar-nav">
                            <li class="ms-3"><%= link_to "Users", users_path, class: "nav-link" %></li>
                        </ul>
                        <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li class="dropdown-item"><%= link_to "My profile", user_path(current_user), class: "nav-link" %></li>
                            <li class="dropdown-divider"></li>
                            <li class="dropdown-item"><%= link_to "Logout", logout_path, data: { "turbo-method": :delete }, class: "nav-link" %></li>
                        </ul>
                    </div>
                <% else %>
                    <ul class="navbar-nav">
                        <li class="nav-item"><%= link_to "Signup", signup_path, class: "nav-link" %></li>
                        <li class="nav-item"><%= link_to "Login", login_path, class: "nav-link" %></li>
                    </ul>
                <% end %>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Microposts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-turbolinks="false">
    <%= render "layouts/navbar" %>
    
    <div class="container">
      <%= render "layouts/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/microposts/_microposts.html.erb
<%#= render "microposts/microposts", microposts: @microposts %>
<% if microposts.any? %>
    <ul class="list-unstyled mt-2">
        <% microposts.each do |mpost| %>
            <li class="d-flex">
                <img class="rounded me-2 mb-5" src="<%= gravatar_url(mpost.user, {size: 64}) %>" alt="">
                <div>
                    <div>
                        <%= link_to mpost.user.name, user_path(mpost.user), class: "text-decoration-none" %>
                        <span class="text-muted">posted at <%= mpost.created_at %></span>
                    </div>
                    <div>
                        <p><%= mpost.content %></p>
                    </div>
                    <div>
                        <!-- 投稿が自分の投稿か? -->
                        <% if current_user == mpost.user %>
                            <%= link_to "Delete", mpost, data: {turbo_method: :delete,  turbo_confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm" %>
                        <% else %>
                            <%= render "favorites/favorite_button", post_item: mpost %>
                        <% end %>
                    </div>
                </div>
            </li>
        <% end %>
    </ul>
    <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/relationships/_follow_button.html.erb
<%#= render "relationships/follow_button", user: @user %>
<% unless current_user == user %>
    <% if current_user.following?(user) %>
        <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), method: :delete) do |f| %>
            <%= hidden_field_tag :follow_id, user.id %>
            <%= f.submit "Unfollow", class: "btn btn-danger w-100" %>
        <% end %>
    <% else %>
        <%= form_with(model: current_user.relationships.build) do |f| %>
            <%= hidden_field_tag :follow_id, user.id %>
            <%= f.submit "Follow", class: "btn btn-primary w-100" %>
        <% end %>
    <% end %>
<% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>
    <div class="row">
        <aside class="col-sm-4">
            <%= form_with(model: @micropost) do |f| %>
                <div class="mb-3">
                    <%= f.text_area :content, class: "form-control", rows: 10 %>
                </div>
                <%= f.submit "Post", class: "btn btn-primary w-100" %>
            <% end %>
        </aside>
        <div class="col-sm-8">
            <%= render "microposts/microposts", microposts: @microposts %>
        </div>
    </div>
<% else %>
    <div class="bg-secondary p-3 p-sm-5 my-4 rounded">
        <div class="text-center text-white">
            <h1>Welcome to the Microposts</h1>
            <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
        </div>
    </div>
<% end %>

app/views/users/_users.html.erb
<%#= render "users", users: @users %>
<%#= render "users/users", users: @followings %>
<%#= render "users/users", users: @followers %>
<% if users.any? %>
    <ul class="list-unstyled">
        <% users.each do |user| %>
            <li class="mb-3 d-flex">
                <img class="rounded me-2" src="<%= gravatar_url(user, {size: 64})%>" alt="">
                <div>
                    <div>
                        <%= user.name %>
                    </div>
                    <p><%= link_to "View profile", user_path(user), class: "text-decoration-none" %></p>
                </div>
            </li>
        <% end %>
    </ul>
    <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/users/followers.html.erb
<div class="row">
    <aside class="col-sm-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"><%= @user.name %></h3>
            </div>
            <div class="card-body">
                <img class="rounded img-fluid" src="<%= gravatar_url(@user, {size: 500})%>" alt="">
            </div>
        </div>
        <%= render "relationships/follow_button", user: @user %>
    </aside>
    
    <div class="col-sm-8">
        <ul class="nav nav-tabs nav-justified mb-3">
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(user_path(@user)) %>" href="<%= user_path(@user) %>">
                    Microposts <span class="badge bg-secondary"><%= @count_posts %></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(followings_user_path(@user)) %>" href="<%= followings_user_path(@user) %>">
                    Followings <span class="badge bg-secondary"><%= @count_followings %></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(followers_user_path(@user)) %>" href="<%= followers_user_path(@user) %>">
                    Followers <span class="badge bg-secondary"><%= @count_followers %></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(likes_user_path(@user)) %>" href="<%= likes_user_path(@user) %>">
                    Favorites <span class="badge bg-secondary"><%= @count_favorites %></span>
                </a>
            </li>
        </ul>
        <%= render "users/users", users: @followers %>
    </div>
</div>

app/views/users/followings.html.erb
<div class="row">
    <aside class="col-sm-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"><%= @user.name %></h3>
            </div>
            <div class="card-body">
                <img class="rounded img-fluid" src="<%= gravatar_url(@user, {size: 500})%>" alt="">
            </div>
        </div>
        <%= render "relationships/follow_button", user: @user %>
    </aside>
    
    <div class="col-sm-8">
        <ul class="nav nav-tabs nav-justified mb-3">
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(user_path(@user)) %>" href="<%= user_path(@user) %>">
                    Microposts <span class="badge bg-secondary"><%= @count_posts %></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(followings_user_path(@user)) %>" href="<%= followings_user_path(@user) %>">
                    Followings <span class="badge bg-secondary"><%= @count_followings %></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(followers_user_path(@user)) %>" href="<%= followers_user_path(@user) %>">
                    Followers <span class="badge bg-secondary"><%= @count_followers %></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(likes_user_path(@user)) %>" href="<%= likes_user_path(@user) %>">
                    Favorites <span class="badge bg-secondary"><%= @count_favorites %></span>
                </a>
            </li>
        </ul>
        <%= render "users/users", users: @followings %>
    </div>
</div>

app/views/users/index.html.erb
<%= render "users", users: @users %>

app/views/users/likes.html.erb
<div class="row">
    <aside class="col-sm-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"><%= @user.name %></h3>
            </div>
            <div class="card-body">
                <img class="rounded img-fluid" src="<%= gravatar_url(@user, {size: 500})%>" alt="">
            </div>
        </div>
        <%= render "relationships/follow_button", user: @user %>
    </aside>
    
    <div class="col-sm-8">
        <ul class="nav nav-tabs nav-justified mb-3">
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(user_path(@user)) %>" href="<%= user_path(@user) %>">
                    Microposts <span class="badge bg-secondary"><%= @count_posts %></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(followings_user_path(@user)) %>" href="<%= followings_user_path(@user) %>">
                    Followings <span class="badge bg-secondary"><%= @count_followings %></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(followers_user_path(@user)) %>" href="<%= followers_user_path(@user) %>">
                    Followers <span class="badge bg-secondary"><%= @count_followers %></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(likes_user_path(@user)) %>" href="<%= likes_user_path(@user) %>">
                    Favorites <span class="badge bg-secondary"><%= @count_favorites %></span>
                </a>
            </li>
        </ul>
        <%= render "microposts/microposts", microposts: @favorites %>
    </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
    <h1>Sign up</h1>
</div>
<div class="row">
    <div class="col-sm-6 offset-sm-3">
        <%= form_with(model: @user) do |f| %>
            <%= render "layouts/error_messages", model: f.object %>
            
            <div class="mb-3">
                <%= f.label :name, "Name" %>
                <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="mb-3">
                <%= f.label :email, "Email" %>
                <%= f.email_field :email, class: "form-control" %>
            </div>
            <div class="mb-3">
                <%= f.label :password, "Password" %>
                <%= f.password_field :password, class: "form-control" %>
            </div>
            <div class="mb-3">
                <%= f.label :password_confirmation, "Confirmation" %>
                <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>
            <%= f.submit "Sign up", class: "btn btn-primary w-100" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <aside class="col-sm-4">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title"><%= @user.name %></h3>
            </div>
            <div class="card-body">
                <img class="rounded img-fluid" src="<%= gravatar_url(@user, {size: 500})%>" alt="">
            </div>
        </div>
        <%= render "relationships/follow_button", user: @user %>
    </aside>
    
    <div class="col-sm-8">
        <ul class="nav nav-tabs nav-justified mb-3">
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(user_path(@user)) %>" href="<%= user_path(@user) %>">
                    Microposts <span class="badge bg-secondary"><%= @count_posts %></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(followings_user_path(@user)) %>" href="<%= followings_user_path(@user) %>">
                    Followings <span class="badge bg-secondary"><%= @count_followings %></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(followers_user_path(@user)) %>" href="<%= followers_user_path(@user) %>">
                    Followers <span class="badge bg-secondary"><%= @count_followers %></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link <%= "active" if current_page?(likes_user_path(@user)) %>" href="<%= likes_user_path(@user) %>">
                    Favorites <span class="badge bg-secondary"><%= @count_favorites %></span>
                </a>
            </li>
        </ul>
        <%= render "microposts/microposts", microposts: @microposts %>
    </div>
</div>